user rating
backstop-protocol/react-client pull request #56
Opened 2020-12-15 14:23 UTC by shmuel-web

# change user rating to "score"
text change

![Screen Shot 2020-12-15 at 16 19 40](https://user-images.githubusercontent.com/13344801/102227069-cf3f3a80-3ef1-11eb-8d18-750b11287698.png)

2020-12-15 15:10 UTC, shmuel-web commented
@yaronvel 
is this missing something?
I think the tooltip could be more descriptive saying something like  "total user rating"
"personal score ..."
maybe a leader board?

2020-12-16 08:00 UTC, yaronvel requested changes

2020-12-16 08:00 UTC, yaronvel commented on src/components/GlobalStats.js
> -                        <h2>User Rating
should change to `User Score`, and also in FAQ, and risk page.

2020-12-17 08:15 UTC, yaronvel approved these changes

2020-12-17 08:15 UTC, merged